name: Upload AAR to Release

on:
  workflow_dispatch:   # manual
  push:
    tags:
      - 'v*'           # hanya tag dengan huruf kecil "v"

permissions:
  contents: write      # penting! biar bisa bikin release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload AAR files to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            libs/release/poing-godot-admob-vungle-v1.0.0-release.aar
            libs/release/poing-godot-admob-meta-v1.0.0-release.aar
            libs/release/poing-godot-admob-adcolony-v1.0.0-release.aar
            libs/release/poing-godot-admob-core-v1.0.1-release.aar
            libs/release/poing-godot-admob-ads-v1.0.1-release.aar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
