name: Upload AAR to Release

on:
  workflow_dispatch:   # manual
  push:
    tags:
      - 'v2*'           # tag lowercase

permissions:
  contents: write      # penting! biar bisa bikin release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true  # otomatis pull LFS saat checkout

      - name: Upload AAR files to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            libs/release/*.aar
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
