name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Configure Android SDK and Install Components
      run: |
        ANDROID_HOME_PATH="/usr/local/lib/android/sdk"
        echo "ANDROID_HOME=$ANDROID_HOME_PATH" >> $GITHUB_ENV
        echo "$ANDROID_HOME_PATH/cmdline-tools/latest/bin" >> $GITHUB_PATH
        yes | $ANDROID_HOME_PATH/cmdline-tools/latest/bin/sdkmanager --licenses \
        && $ANDROID_HOME_PATH/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "build-tools;34.0.0" \
          "platforms;android-34" \
          "cmake;3.10.2.4988404" \
          "ndk;23.2.8568313"

    - name: Decode and Save Keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSAYA }}
      run: |
       mkdir - app
        echo "$KEYSTORE_BASE64" | base64 --decode > app/keystore.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      env:
        # Gunakan GitHub Secrets sebagai variabel lingkungan untuk Gradle
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        ./gradlew assembleRelease --stacktrace \
          -Prelease_keystore_file=keystore.jks \
          -Prelease_keystore_password="$KEYSTORE_PASSWORD" \
          -Prelease_keystore_alias="$KEY_ALIAS" \
          -Prelease_key_password="$KEY_PASSWORD"
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android_release
        path: app/build/outputs/apk/release/android_release.apk
